import { useSelector } from "react-redux";
import Card from "../Card/Card";
import style from "./CardsContainer.module.css";



const CardsContainer = () => {
  const countries = useSelector((state)=>state.countries)
//   const countries = [
//     {
//       id: "CXR",
//       name: "Territory of Christmas Island",
//       imageFlag: "https://flagcdn.com/w320/cx.png",
//       continent: "Asia",
//       capital: "Flying Fish Cove",
//       subRegion: "Australia and New Zealand",
//       area: 135,
//       population: 2072,
//     },
//     {
//       id: "SLB",
//       name: "Solomon Islands",
//       imageFlag: "https://flagcdn.com/w320/sb.png",
//       continent: "Oceania",
//       capital: "Honiara",
//       subRegion: "Melanesia",
//       area: 28896,
//       population: 686878,
//     },
//     {
//       id: "TWN",
//       name: "Republic of China (Taiwan)",
//       imageFlag: "https://flagcdn.com/w320/tw.png",
//       continent: "Asia",
//       capital: "Taipei",
//       subRegion: "Eastern Asia",
//       area: 36193,
//       population: 23503349,
//     },
//     {
//       id: "UMI",
//       name: "United States Minor Outlying Islands",
//       imageFlag: "https://flagcdn.com/w320/um.png",
//       continent: "Oceania",
//       capital: null,
//       subRegion: "North America",
//       area: 34,
//       population: 300,
//     },
//     {
//       id: "MKD",
//       name: "Republic of North Macedonia",
//       imageFlag: "https://flagcdn.com/w320/mk.png",
//       continent: "Europe",
//       capital: "Skopje",
//       subRegion: "Southeast Europe",
//       area: 25713,
//       population: 2077132,
//     },
//     {
//       id: "JOR",
//       name: "Hashemite Kingdom of Jordan",
//       imageFlag: "https://flagcdn.com/w320/jo.png",
//       continent: "Asia",
//       capital: "Amman",
//       subRegion: "Western Asia",
//       area: 89342,
//       population: 10203140,
//     },
//     {
//       id: "RUS",
//       name: "Russian Federation",
//       imageFlag: "https://flagcdn.com/w320/ru.png",
//       continent: "Europe",
//       capital: "Moscow",
//       subRegion: "Eastern Europe",
//       area: 17098242,
//       population: 144104080,
//     },
//     {
//       id: "SLV",
//       name: "Republic of El Salvador",
//       imageFlag: "https://flagcdn.com/w320/sv.png",
//       continent: "North America",
//       capital: "San Salvador",
//       subRegion: "Central America",
//       area: 21041,
//       population: 6486201,
//     },
//     {
//       id: "THA",
//       name: "Kingdom of Thailand",
//       imageFlag: "https://flagcdn.com/w320/th.png",
//       continent: "Asia",
//       capital: "Bangkok",
//       subRegion: "South-Eastern Asia",
//       area: 513120,
//       population: 69799978,
//     },
//     {
//       id: "MNE",
//       name: "Montenegro",
//       imageFlag: "https://flagcdn.com/w320/me.png",
//       continent: "Europe",
//       capital: "Podgorica",
//       subRegion: "Southeast Europe",
//       area: 13812,
//       population: 621718,
//     },
//     {
//       id: "TON",
//       name: "Kingdom of Tonga",
//       imageFlag: "https://flagcdn.com/w320/to.png",
//       continent: "Oceania",
//       capital: "Nuku'alofa",
//       subRegion: "Polynesia",
//       area: 747,
//       population: 105697,
//     },
//     {
//       id: "PCN",
//       name: "Pitcairn Group of Islands",
//       imageFlag: "https://flagcdn.com/w320/pn.png",
//       continent: "Oceania",
//       capital: "Adamstown",
//       subRegion: "Polynesia",
//       area: 47,
//       population: 56,
//     },
//     {
//       id: "LBR",
//       name: "Republic of Liberia",
//       imageFlag: "https://flagcdn.com/w320/lr.png",
//       continent: "Africa",
//       capital: "Monrovia",
//       subRegion: "Western Africa",
//       area: 111369,
//       population: 5057677,
//     },
//     {
//       id: "TCA",
//       name: "Turks and Caicos Islands",
//       imageFlag: "https://flagcdn.com/w320/tc.png",
//       continent: "North America",
//       capital: "Cockburn Town",
//       subRegion: "Caribbean",
//       area: 948,
//       population: 38718,
//     },
//     {
//       id: "CUB",
//       name: "Republic of Cuba",
//       imageFlag: "https://flagcdn.com/w320/cu.png",
//       continent: "North America",
//       capital: "Havana",
//       subRegion: "Caribbean",
//       area: 109884,
//       population: 11326616,
//     },
//     {
//       id: "CHL",
//       name: "Republic of Chile",
//       imageFlag: "https://flagcdn.com/w320/cl.png",
//       continent: "South America",
//       capital: "Santiago",
//       subRegion: "South America",
//       area: 756102,
//       population: 19116209,
//     },
//     {
//       id: "GNQ",
//       name: "Republic of Equatorial Guinea",
//       imageFlag: "https://flagcdn.com/w320/gq.png",
//       continent: "Africa",
//       capital: "Malabo",
//       subRegion: "Middle Africa",
//       area: 28051,
//       population: 1402985,
//     },
//     {
//       id: "CYM",
//       name: "Cayman Islands",
//       imageFlag: "https://flagcdn.com/w320/ky.png",
//       continent: "North America",
//       capital: "George Town",
//       subRegion: "Caribbean",
//       area: 264,
//       population: 65720,
//     },
//     {
//       id: "PYF",
//       name: "French Polynesia",
//       imageFlag: "https://flagcdn.com/w320/pf.png",
//       continent: "Oceania",
//       capital: "PapeetÄ“",
//       subRegion: "Polynesia",
//       area: 4167,
//       population: 280904,
//     },
//     {
//       id: "MOZ",
//       name: "Republic of Mozambique",
//       imageFlag: "https://flagcdn.com/w320/mz.png",
//       continent: "Africa",
//       capital: "Maputo",
//       subRegion: "Eastern Africa",
//       area: 801590,
//       population: 31255435,
//     },
//     {
//       id: "BLM",
//       name: "Collectivity of Saint BarthÃ©lemy",
//       imageFlag: "https://flagcdn.com/w320/bl.png",
//       continent: "North America",
//       capital: "Gustavia",
//       subRegion: "Caribbean",
//       area: 21,
//       population: 4255,
//     },
//     {
//       id: "VUT",
//       name: "Republic of Vanuatu",
//       imageFlag: "https://flagcdn.com/w320/vu.png",
//       continent: "Oceania",
//       capital: "Port Vila",
//       subRegion: "Melanesia",
//       area: 12189,
//       population: 307150,
//     },
//     {
//       id: "CCK",
//       name: "Territory of the Cocos (Keeling) Islands",
//       imageFlag: "https://flagcdn.com/w320/cc.png",
//       continent: "Asia",
//       capital: "West Island",
//       subRegion: "Australia and New Zealand",
//       area: 14,
//       population: 544,
//     },
//     {
//       id: "TLS",
//       name: "Democratic Republic of Timor-Leste",
//       imageFlag: "https://flagcdn.com/w320/tl.png",
//       continent: "Oceania",
//       capital: "Dili",
//       subRegion: "South-Eastern Asia",
//       area: 14874,
//       population: 1318442,
//     },
//     {
//       id: "FJI",
//       name: "Republic of Fiji",
//       imageFlag: "https://flagcdn.com/w320/fj.png",
//       continent: "Oceania",
//       capital: "Suva",
//       subRegion: "Melanesia",
//       area: 18272,
//       population: 896444,
//     },
//     {
//       id: "ESH",
//       name: "Sahrawi Arab Democratic Republic",
//       imageFlag: "https://flagcdn.com/w320/eh.png",
//       continent: "Africa",
//       capital: "El AaiÃºn",
//       subRegion: "Northern Africa",
//       area: 266000,
//       population: 510713,
//     },
//     {
//       id: "MCO",
//       name: "Principality of Monaco",
//       imageFlag: "https://flagcdn.com/w320/mc.png",
//       continent: "Europe",
//       capital: "Monaco",
//       subRegion: "Western Europe",
//       area: 2,
//       population: 39244,
//     },
//     {
//       id: "SRB",
//       name: "Republic of Serbia",
//       imageFlag: "https://flagcdn.com/w320/rs.png",
//       continent: "Europe",
//       capital: "Belgrade",
//       subRegion: "Southeast Europe",
//       area: 88361,
//       population: 6908224,
//     },
//     {
//       id: "KOR",
//       name: "Republic of Korea",
//       imageFlag: "https://flagcdn.com/w320/kr.png",
//       continent: "Asia",
//       capital: "Seoul",
//       subRegion: "Eastern Asia",
//       area: 100210,
//       population: 51780579,
//     },
//     {
//       id: "TCD",
//       name: "Republic of Chad",
//       imageFlag: "https://flagcdn.com/w320/td.png",
//       continent: "Africa",
//       capital: "N'Djamena",
//       subRegion: "Middle Africa",
//       area: 1284000,
//       population: 16425859,
//     },
//     {
//       id: "ATF",
//       name: "Territory of the French Southern and Antarctic Lands",
//       imageFlag: "https://flagcdn.com/w320/tf.png",
//       continent: "Antarctica",
//       capital: "Port-aux-FranÃ§ais",
//       subRegion: null,
//       area: 7747,
//       population: 400,
//     },
//     {
//       id: "SVN",
//       name: "Republic of Slovenia",
//       imageFlag: "https://flagcdn.com/w320/si.png",
//       continent: "Europe",
//       capital: "Ljubljana",
//       subRegion: "Central Europe",
//       area: 20273,
//       population: 2100126,
//     },
//     {
//       id: "ROU",
//       name: "Romania",
//       imageFlag: "https://flagcdn.com/w320/ro.png",
//       continent: "Europe",
//       capital: "Bucharest",
//       subRegion: "Southeast Europe",
//       area: 238391,
//       population: 19286123,
//     },
//     {
//       id: "NGA",
//       name: "Federal Republic of Nigeria",
//       imageFlag: "https://flagcdn.com/w320/ng.png",
//       continent: "Africa",
//       capital: "Abuja",
//       subRegion: "Western Africa",
//       area: 923768,
//       population: 206139587,
//     },
//     {
//       id: "HUN",
//       name: "Hungary",
//       imageFlag: "https://flagcdn.com/w320/hu.png",
//       continent: "Europe",
//       capital: "Budapest",
//       subRegion: "Central Europe",
//       area: 93028,
//       population: 9749763,
//     },
//     {
//       id: "SXM",
//       name: "Sint Maarten",
//       imageFlag: "https://flagcdn.com/w320/sx.png",
//       continent: "North America",
//       capital: "Philipsburg",
//       subRegion: "Caribbean",
//       area: 34,
//       population: 40812,
//     },
//     {
//       id: "IRN",
//       name: "Islamic Republic of Iran",
//       imageFlag: "https://flagcdn.com/w320/ir.png",
//       continent: "Asia",
//       capital: "Tehran",
//       subRegion: "Southern Asia",
//       area: 1648195,
//       population: 83992953,
//     },
//     {
//       id: "SYC",
//       name: "Republic of Seychelles",
//       imageFlag: "https://flagcdn.com/w320/sc.png",
//       continent: "Africa",
//       capital: "Victoria",
//       subRegion: "Eastern Africa",
//       area: 452,
//       population: 98462,
//     },
//   ];
// console.log(countries);
return (
	<div className={style.cards}>
      {countries.map(e=>{
        return<Card
          name={e.name}
          id={e.id}
          imageFlag={e.imageFlag}
          continent={e.continent}
          capital={e.capital}
          subRegion={e.subRegion}
          area={e.area}
          population={e.population}
		  key={e.id}
        />
      })}
    </div>
  );
};

export default CardsContainer;
